CREATE SEQUENCE REDEX.SEQ_COLETOR_FOTOS  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

CREATE TABLE REDEX.TB_COLETOR_FOTOS(
    AUTONUM INT NOT NULL PRIMARY KEY,
    AUTONUM_PROCESSO INT NOT NULL,
    ARQUIVO VARCHAR2(50),
    TIPO NUMBER(1) NOT NULL,
    USUARIO INT,
    DT_INCLUSAO DATE DEFAULT SYSDATE
);

ALTER TABLE REDEX.TB_TALIE_ITEM ADD FLAG_AVARIADO NUMBER(1);
ALTER TABLE REDEX.TB_NOTAS_FISCAIS ADD PESO_BRUTO NUMBER(12,3);

CREATE OR REPLACE VIEW REDEX.VW_CONSULTA_CNTR_COLETOR 
(ID_CONTEINER,AUTONUM_PATIO, TAMANHO, STATUS, RESERVA,REFERENCIA, CLIENTE,ARMADOR,DEADLINE,LACRES,LACRE_CONTROLE,ENTRADA) as
SELECT
DISTINCT
P.ID_CONTEINER,
P.AUTONUM_PATIO,
P.TAMANHO,
CASE WHEN NVL (T.flag_estufagem, 0) = 0 THEN 'VAZIO' ELSE 'ESTUFADO' END  AS STATUS,
BOO.REFERENCE AS RESERVA,
BOO.INSTRUCAO AS REFERENCIA,
PARC.RAZAO AS CLIENTE,
ARM.DESCRICAO ARMADOR,
V.DT_DEAD_LINE DEADLINE,
(
    SELECT
        rtrim(
            xmlagg(xmlelement(
                e,
                (
                    LACRE
                )
                 || ','
            ) ).extract('//text()'),
            ','
        ) Lacres
    FROM
        REDEX.TB_PATIO_LACRES
    WHERE
        AUTONUM_PATIO = P.AUTONUM_PATIO    
) As Lacres,
CASE WHEN PL.DT_LACRE_RECEPCAO IS NULL THEN 'NÃO' ELSE 'SIM' END LACRE_CONTROLE,
P.DT_ENTRADA AS ENTRADA
FROM REDEX.TB_PATIO P
LEFT JOIN REDEX.TB_TALIE T ON P.AUTONUM_PATIO = T.AUTONUM_PATIO
LEFT JOIN REDEX.TB_BOOKING_CARGA BC ON P.AUTONUM_BCG = BC.AUTONUM_BCG
LEFT JOIN REDEX.TB_BOOKING BOO  ON BC.AUTONUM_BOO = BOO.AUTONUM_BOO
LEFT JOIN REDEX.TB_VIAGENS V ON BOO.AUTONUM_VIA = V.AUTONUM_VIA
LEFT JOIN REDEX.TB_CAD_PARCEIROS PARC ON BOO.AUTONUM_PARCEIRO =  PARC.AUTONUM
LEFT JOIN REDEX.TB_CAD_ARMADOR ARM ON BOO.AUTONUM_ARM = ARM.AUTONUM_ARM 
LEFT JOIN REDEX.TB_PATIO_LACRES PL ON PL.AUTONUM_PATIO = P.AUTONUM_PATIO;
COMMENT ON TABLE REDEX.VW_CONSULTA_CNTR_COLETOR  IS 'V_20181017';

alter table REDEX.tb_patio_lacres add AUTONUM_USU NUMBER(5,0);
alter table REDEX.tb_patio_lacres add FLAG_VALIDADO NUMBER(1,0);

COMMENT ON COLUMN REDEX.TB_PATIO_LACRES.AUTONUM_USU IS 'CÓDIGO DO USUÁRIO';
COMMENT ON COLUMN REDEX.TB_PATIO_LACRES.FLAG_VALIDADO IS 'INDICA SE OS LACRES FORAM VALIDADOS';


UPDATE REDEX.tb_patio_lacres PL
   SET ( PL.AUTONUM_USU) = (SELECT U.AUTONUM_USU
                         FROM REDEX.tb_cad_usuarios U
                        WHERE PL.USUARIO = U.USUARIO)
 WHERE EXISTS (
    SELECT 1
      FROM REDEX.tb_cad_usuarios U
     WHERE PL.USUARIO = U.USUARIO );
     

CREATE SEQUENCE REDEX.SEQ_PATIO_LACRES_FOTOS  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;

CREATE TABLE REDEX.TB_PATIO_LACRES_FOTOS(
    AUTONUM INT NOT NULL PRIMARY KEY,
    ID_CONTEINER  VARCHAR2(12 BYTE) NOT NULL,
    ARQUIVO VARCHAR2(50),
    USUARIO INT,
    DT_INCLUSAO DATE DEFAULT SYSDATE
);	 

COMMENT ON COLUMN REDEX.TB_PATIO_LACRES_FOTOS.AUTONUM IS 'SEQUENCIAL SEQ_PATIO_LACRES_FOTOS';
COMMENT ON COLUMN REDEX.TB_PATIO_LACRES_FOTOS.ID_CONTEINER IS 'CONTÊINER';
COMMENT ON COLUMN REDEX.TB_PATIO_LACRES_FOTOS.ARQUIVO IS 'NOME DO ARQUIVO';
COMMENT ON COLUMN REDEX.TB_PATIO_LACRES_FOTOS.USUARIO IS 'USUÁRIO QUE FEZ UPLOAD DO ARQUIVO';
COMMENT ON COLUMN REDEX.TB_PATIO_LACRES_FOTOS.DT_INCLUSAO IS 'DATA DO UPLOAD';
