--- MATIRA
USE [REDEX]

CREATE TABLE [dbo].[TB_LOG_COLETOR](
	AUTONUM int IDENTITY(1,1) NOT NULL,
	[DATA] datetime,
	ORIGEM [nvarchar](255),
	MENSAGEM [nvarchar](1000),
	STACK_TRACE nvarchar(4000),
	USUARIO int,
PRIMARY KEY CLUSTERED 
(
	AUTONUM ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TB_LOG_COLETOR] ADD  DEFAULT (getdate()) FOR [DATA]
GO

EXEC sys.sp_addextendedproperty @name=N'ORIGEM', @value=N'Tela de Origem' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TB_LOG_COLETOR', @level2type=N'COLUMN',@level2name=N'ORIGEM'
GO

EXEC sys.sp_addextendedproperty @name=N'MENSAGEM', @value=N'Mensagem de Erro' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TB_LOG_COLETOR', @level2type=N'COLUMN',@level2name=N'MENSAGEM'
GO

EXEC sys.sp_addextendedproperty @name=N'STACK_TRACE', @value=N'Stack do Erro' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TB_LOG_COLETOR', @level2type=N'COLUMN',@level2name=N'STACK_TRACE'
GO

USE [REDEX]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create procedure [dbo].[sp_Coletor_REDEX_Identity]
@select as varchar(max)
as
exec (@select)
return	



USE [redex]
GO

GRANT INSERT ON [dbo].[TB_LOG_COLETOR] TO [linked_ibiza]

GO

USE REDEX;   
GRANT EXECUTE ON OBJECT::dbo.calculaTempo  
    TO Linked_IBIZA;  
GO  


USE [OPERADOR]
GO
CREATE USER [linked_ibiza] FOR LOGIN [linked_ibiza]
GRANT SELECT ON [dbo].[TB_CAD_TRANSPORTADORAS] TO [linked_ibiza]
GO

USE SGIPA;
CREATE USER linked_ibiza FROM LOGIN linked_ibiza;
GRANT CONTROL ON DATABASE::SGIPA TO linked_ibiza;
GO


USE REDEX;   
GRANT EXECUTE ON OBJECT::dbo.sp_Coletor_REDEX_Identity  
    TO linked_ibiza;  
GO  

USE [REDEX]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_AGENDAMENTOS_REDEX] (ID_AGENDAMENTO, NumProtocolo, AnoProtocolo, PROTOCOLO, PERIODO, MOTORISTA, CNH, PLACA_CAVALO, PLACA_CARRETA, PERIODO_INICIAL, PERIODO_FINAL, TIPO) 
AS
/* TIPO 4 => Agendamento Carga Solta Carregamento*/ SELECT A.AUTONUM, A.NUM_PROTOCOLO as NumProtocolo , CONVERT(VARCHAR, A.ANO_PROTOCOLO) AS AnoProtocolo, A.NUM_PROTOCOLO + '/' + CONVERT(VARCHAR, A.ANO_PROTOCOLO) AS PROTOCOLO, CONVERT(VARCHAR, F.PERIODO_INICIAL, 103) 
                         + ' - ' + CONVERT(VARCHAR, F.PERIODO_FINAL, 108) AS PERIODO, D .NOME AS MOTORISTA, D .CNH, E.PLACA_CAVALO, E.PLACA_CARRETA, F.PERIODO_INICIAL, F.PERIODO_FINAL, 1 AS TIPO
FROM            dbo.TB_AGENDAMENTO_WEB_CNTR_CA AS A INNER JOIN
                         dbo.TB_BOOKING AS B ON A.RESERVA = B.REFERENCE INNER JOIN
                         dbo.TB_VIAGENS AS C ON B.AUTONUM_VIA = C.AUTONUM_VIA INNER JOIN
                         IBIZA.SGIPA.dbo.TB_AG_MOTORISTAS AS D ON A.AUTONUM_MOTORISTA = D .AUTONUM INNER JOIN
                         IBIZA.SGIPA.dbo.TB_AG_VEICULOS AS E ON A.AUTONUM_VEICULO = E.AUTONUM LEFT OUTER JOIN
                         dbo.TB_GD_RESERVA AS F ON A.AUTONUM_GD_RESERVA = F.AUTONUM_GD_RESERVA
UNION
SELECT        A.AUTONUM_GD_CNTR, A.NUM_PROTOCOLO as NumProtocolo , CONVERT(VARCHAR, A.ANO_PROTOCOLO) AS AnoProtocolo, A.NUM_PROTOCOLO + '/' + CONVERT(VARCHAR, A.ANO_PROTOCOLO) AS PROTOCOLO, CONVERT(VARCHAR, F.PERIODO_INICIAL, 103) + ' - ' + CONVERT(VARCHAR, F.PERIODO_FINAL, 108) 
                         AS PERIODO, D .NOME AS MOTORISTA, D .CNH, E.PLACA_CAVALO, E.PLACA_CARRETA, F.PERIODO_INICIAL, F.PERIODO_FINAL, 2 AS TIPO
FROM            dbo.TB_GD_CONTEINER AS A INNER JOIN
                         dbo.TB_BOOKING AS B ON A.REFERENCE = B.REFERENCE INNER JOIN
                         dbo.TB_VIAGENS AS C ON B.AUTONUM_VIA = C.AUTONUM_VIA INNER JOIN
                         IBIZA.SGIPA.dbo.TB_AG_MOTORISTAS AS D ON A.AUTONUM_GD_MOTORISTA = D .AUTONUM INNER JOIN
                         IBIZA.SGIPA.dbo.TB_AG_VEICULOS AS E ON A.AUTONUM_VEICULO = E.AUTONUM LEFT OUTER JOIN
                         dbo.TB_GD_RESERVA AS F ON A.AUTONUM_GD_RESERVA = F.AUTONUM_GD_RESERVA
UNION
SELECT        A.AUTONUM, A.NUM_PROTOCOLO as NumProtocolo , CONVERT(VARCHAR, A.ANO_PROTOCOLO) AS AnoProtocolo, A.NUM_PROTOCOLO + '/' + CONVERT(VARCHAR, A.ANO_PROTOCOLO) AS PROTOCOLO, CONVERT(VARCHAR, F.PERIODO_INICIAL, 103) + ' - ' + CONVERT(VARCHAR, F.PERIODO_FINAL, 108) AS PERIODO, 
                         D .NOME AS MOTORISTA, D .CNH, E.PLACA_CAVALO, E.PLACA_CARRETA, F.PERIODO_INICIAL, F.PERIODO_FINAL, 3 AS TIPO
FROM            dbo.TB_AGENDAMENTO_WEB_CS AS A INNER JOIN
                         dbo.TB_BOOKING AS B ON A.RESERVA = B.REFERENCE INNER JOIN
                         dbo.TB_VIAGENS AS C ON B.AUTONUM_VIA = C.AUTONUM_VIA INNER JOIN
                         IBIZA.SGIPA.dbo.TB_AG_MOTORISTAS AS D ON A.AUTONUM_MOTORISTA = D .AUTONUM INNER JOIN
                         IBIZA.SGIPA.dbo.TB_AG_VEICULOS AS E ON A.AUTONUM_VEICULO = E.AUTONUM LEFT OUTER JOIN
                         dbo.TB_GD_RESERVA AS F ON A.AUTONUM_GD_RESERVA = F.AUTONUM_GD_RESERVA LEFT OUTER JOIN
                         dbo.TB_CAD_PARCEIROS AS G ON B.AUTONUM_EXPORTADOR = G.AUTONUM
UNION
SELECT        A.AUTONUM, A.NUM_PROTOCOLO as NumProtocolo , CONVERT(VARCHAR, A.ANO_PROTOCOLO) AS AnoProtocolo, A.NUM_PROTOCOLO + '/' + CONVERT(VARCHAR, A.ANO_PROTOCOLO) AS PROTOCOLO, CONVERT(VARCHAR, F.PERIODO_INICIAL, 103) + ' - ' + CONVERT(VARCHAR, F.PERIODO_FINAL, 108) AS PERIODO, 
                         D .NOME AS MOTORISTA, D .CNH, E.PLACA_CAVALO, E.PLACA_CARRETA, F.PERIODO_INICIAL, F.PERIODO_FINAL, 4 AS TIPO
FROM            dbo.TB_AGENDAMENTO_WEB_CS_CA AS A INNER JOIN
                         dbo.TB_BOOKING AS B ON A.RESERVA = B.REFERENCE INNER JOIN
                         dbo.TB_VIAGENS AS C ON A.AUTONUM_VIAGEM = C.AUTONUM_VIA INNER JOIN
                         IBIZA.SGIPA.dbo.TB_AG_MOTORISTAS AS D ON A.AUTONUM_MOTORISTA = D .AUTONUM INNER JOIN
                         IBIZA.SGIPA.dbo.TB_AG_VEICULOS AS E ON A.AUTONUM_VEICULO = E.AUTONUM LEFT OUTER JOIN
                         dbo.TB_GD_RESERVA AS F ON A.AUTONUM_GD_RESERVA = F.AUTONUM_GD_RESERVA
GO

-- IBIZA
EXEC sp_serveroption
   @server = 'MATIRA',
   @optname = 'rpc out',
   @optvalue = 'True';