'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TalieColetorDescarga

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''btnHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHome As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLogout As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''hddnTalieId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddnTalieId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hddnTalieItensSelIdx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddnTalieItensSelIdx As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hddnNFItensSelIdx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddnNFItensSelIdx As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hddnConteinerId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddnConteinerId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hddnGateId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddnGateId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hddnReserva control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddnReserva As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hddnNFId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddnNFId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hddnCrossDocking control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddnCrossDocking As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hddnNFItemId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddnNFItemId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hddnNovoNFItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddnNovoNFItem As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hddnEmbalagemId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddnEmbalagemId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hddnProdutoId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddnProdutoId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hddnClienteId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddnClienteId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hddnReservaId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddnReservaId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hddnTalieItemId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddnTalieItemId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hddnTipoDescarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddnTipoDescarga As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hddnRowIndex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddnRowIndex As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hddnOrigem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hddnOrigem As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btSair control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btSair As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Validacoes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Validacoes As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''lblMensagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensagem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbRegistro As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblTalieNumero control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTalieNumero As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkTalieFechado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTalieFechado As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlCrossDocking control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCrossDocking As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chkCrossdocking control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCrossdocking As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtInicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInicio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFIM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFIM As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCliente As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPlaca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlaca As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlConteiner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlConteiner As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtConteiner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConteiner As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtReserva control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReserva As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cbConferente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbConferente As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cbEquipe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbEquipe As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cbModo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbModo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkEstufagemCompleta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEstufagemCompleta As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''pnlLimpar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLimpar As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnTalieCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTalieCancelar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlGravar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGravar As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnTalieGravar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTalieGravar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlFinalizar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFinalizar As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlEdicaoItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlEdicaoItem As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cbNF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbNF As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtEmbalagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmbalagem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtProduto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProduto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtQtdeNF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtdeNF As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtQtdeDescarga control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtdeDescarga As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtComprimento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComprimento As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLargura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLargura As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAltura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAltura As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPeso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPeso As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''itemLocalArmazem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents itemLocalArmazem As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtLocal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLocal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnItemCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnItemCancelar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''btnItemGravar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnItemGravar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''grdItens control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdItens As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''FiltrarTalie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FiltrarTalie As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtFiltroRegistro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFiltroRegistro As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFiltroTalie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFiltroTalie As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnPesquisarTalie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPesquisarTalie As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''grdTalie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdTalie As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnConsultarTalies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConsultarTalies As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TabName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabName As Global.System.Web.UI.WebControls.HiddenField
End Class
